language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

env:
    - SYMFONY_VERSION=4.1.* # (until 07/2019)
    - SYMFONY_VERSION=4.2.* # (until 01/2020)
    - SYMFONY_VERSION=4.3.* # (until 07/2020)
    - SYMFONY_VERSION=4.4.* # LTS (11/2019, until 11/2023)
    - SYMFONY_VERSION=5.0.* # (until 07/2020)
    - DEPENDENCIES=dev

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability $DEPENDENCIES; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
    - composer update

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/phpunit --coverage-text --verbose

after_success:
    - travis_retry php vendor/bin/php-coveralls

matrix:
    exclude:
        - php: 7.1
          env: SYMFONY_VERSION=5.0.* # requires PHP ^7.2.5
    allow_failures:
        - env: DEPENDENCIES=dev
        - php: nightly

notifications:
    email:
        - "gregurco.vlad@gmail.com"
